name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build jar

      - name: List build/libs directory contents
        run: ls -l build/libs

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-keychain-app-jar
          path: build/libs/java-keychain-app-*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: java-keychain-app-jar
          path: ./release-jars

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release-jars/java-keychain-app-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
